# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoExample < Formula
  desc "Example"
  homepage "https://github.com/profiprog/go-exmaple"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/profiprog/go-exmaple/releases/download/v0.1.1/go-example_v0.1.1_darwin_arm64.tar.gz"
      sha256 "ed760db970a72fde8b9ae2b38ed22667bbd4f259b66fdbcfac6252f94c835a69"

      def install
        bin.install "go-example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/go-exmaple/releases/download/v0.1.1/go-example_v0.1.1_darwin_amd64.tar.gz"
      sha256 "93994c9eef6ab49ea397adcc7c4f074b8d581b74782f78e4167cc807c32c229f"

      def install
        bin.install "go-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/profiprog/go-exmaple/releases/download/v0.1.1/go-example_v0.1.1_linux_arm64.tar.gz"
      sha256 "67140df2567d8d12068c9f739ee24d874b7695a67c2ef1d19c928ba272b3aa7f"

      def install
        bin.install "go-example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/go-exmaple/releases/download/v0.1.1/go-example_v0.1.1_linux_amd64.tar.gz"
      sha256 "018608c76fb6569d7260f8ad2ab521d28c010a174603d9757c14b0c6b7104d0c"

      def install
        bin.install "go-example"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/profiprog/go-exmaple
    EOS
  end

  test do
    system "#{bin}/go-example version"
  end
end
