# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoExample < Formula
  desc "Example"
  homepage "https://github.com/profiprog/go-example"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/profiprog/go-example/releases/download/v0.1.1/go-example_v0.1.1_darwin_arm64.tar.gz"
      sha256 "0b606f5317c25ecb39174cc8ae3c20952a0e77b004bc4ab713211a2d10ea79bb"

      def install
        bin.install "go-example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/go-example/releases/download/v0.1.1/go-example_v0.1.1_darwin_amd64.tar.gz"
      sha256 "b877282e9c6eddab646c99d66d67f8a044bc7ad67f16639d9e77ca9a66b81c5a"

      def install
        bin.install "go-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/go-example/releases/download/v0.1.1/go-example_v0.1.1_linux_amd64.tar.gz"
      sha256 "cab676a6024756a7b2e33b34285d19605033d86573883511357d3945b3913c73"

      def install
        bin.install "go-example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/profiprog/go-example/releases/download/v0.1.1/go-example_v0.1.1_linux_arm64.tar.gz"
      sha256 "532e3356470f2cd1c5e7ef71c1e8fafafa0fea35ba961265fd36e7f73cf05816"

      def install
        bin.install "go-example"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/profiprog/go-example
    EOS
  end

  test do
    system "#{bin}/go-example version"
  end
end
