# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Res < Formula
  desc "Tool for filtering kubernetes resources defined in yaml"
  homepage "https://github.com/profiprog/res"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/res/releases/download/v0.3.0/res_v0.3.0_darwin_amd64.tar.gz"
      sha256 "19efad4bc679b4bbc9741f15f9c1a19b2d76ae6926b0c3ea0fc832c716756c07"

      define_method(:install) do
        bin.install "res"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/profiprog/res/releases/download/v0.3.0/res_v0.3.0_darwin_arm64.tar.gz"
      sha256 "e07e32b85b73f83f9af974e112d5d603b3d533166c72e871ef181fc525e9772a"

      define_method(:install) do
        bin.install "res"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/profiprog/res/releases/download/v0.3.0/res_v0.3.0_linux_amd64.tar.gz"
      sha256 "c1afb06eb7194dcced637171c007527b7e63b7e6695ac31b359bfb86e9f4e2b6"
      define_method(:install) do
        bin.install "res"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/profiprog/res/releases/download/v0.3.0/res_v0.3.0_linux_arm64.tar.gz"
      sha256 "4e3babaf22b34f21ff7bafa0f8991486af2e894cddb196007c42a05e0f5b60ad"
      define_method(:install) do
        bin.install "res"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/profiprog/res
    EOS
  end

  test do
    system "#{bin}/res"
  end
end
