# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Res < Formula
  desc "Example"
  homepage "https://github.com/profiprog/res"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/profiprog/res/releases/download/v0.1.0/res_v0.1.0_darwin_arm64.tar.gz"
      sha256 "1162b6dfb934bebaa639845b12eb831df6b083a1d358028368d63a7ea62ad0dd"

      def install
        bin.install "res"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/res/releases/download/v0.1.0/res_v0.1.0_darwin_amd64.tar.gz"
      sha256 "a39b252629c759a12897a018ab0851e174c3312dfea69e73662b3a2d47acf008"

      def install
        bin.install "res"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/profiprog/res/releases/download/v0.1.0/res_v0.1.0_linux_arm64.tar.gz"
      sha256 "175540424e80f96e8a1df8a436f48057da8b52a88bcfb08c624a5eb9532e6a03"

      def install
        bin.install "res"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/res/releases/download/v0.1.0/res_v0.1.0_linux_amd64.tar.gz"
      sha256 "8e8cc9e36a31c2d85b57e863e265b7e3e21d89fcb1fdb020d48bc7b8de597808"

      def install
        bin.install "res"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/profiprog/res
    EOS
  end

  test do
    system "#{bin}/res"
  end
end
