# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Res < Formula
  desc "Example"
  homepage "https://github.com/profiprog/res"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/profiprog/res/releases/download/v0.1.1/res_v0.1.1_darwin_arm64.tar.gz"
      sha256 "b249b5c455e63e8b2cf63442e791c974fd7dfdfc1412217805d040eadf46540d"

      def install
        bin.install "res"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/res/releases/download/v0.1.1/res_v0.1.1_darwin_amd64.tar.gz"
      sha256 "c0469e42d228bb7e130a0789ba510cd401786bd7c945dc6a4e44994f5b0a5580"

      def install
        bin.install "res"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/profiprog/res/releases/download/v0.1.1/res_v0.1.1_linux_arm64.tar.gz"
      sha256 "4ef65ef2cccc872ce31e362fe96e6d2c3a5fe7c6744165c4159d8b23be184c84"

      def install
        bin.install "res"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/profiprog/res/releases/download/v0.1.1/res_v0.1.1_linux_amd64.tar.gz"
      sha256 "a681966a8e97be57941036345eb671dc907ec0218cf9b37d473c6614c0427530"

      def install
        bin.install "res"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/profiprog/res
    EOS
  end

  test do
    system "#{bin}/res"
  end
end
